services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: friends_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - /var/www/vendor
    networks:
      - laravel_network

  nginx:
    image: nginx:latest
    container_name: friends_nginx
    restart: unless-stopped
    ports:
      - "8082:8082"
    volumes:
      - .:/var/www
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network


networks:
  laravel_network:
    external: true


volumes:
  mysql_data:
